add options for logging levels

diff --git a/folder-sync b/folder-sync
--- a/folder-sync
+++ b/folder-sync
@@ -16,19 +16,19 @@
 # functions
 ###########################
 
-function catchStdErr2() {
-    local -n v="$1";
-    shift && { v="$("$@" 2>&1 1>&3 3>&-)"; } 3>&1;
-    echo "$v"
-}
+#function catchStdErr2() {
+#    local -n v="$1";
+#    shift && { v="$("$@" 2>&1 1>&3 3>&-)"; } 3>&1;
+#    echo "$v"
+#}
 
 function catchStdErr() {
     local err=''
     { err="$("$@" 2>&1 1>&3 3>&-)"; } 3>&1
 
-    if [ "$err" != '' ]
+    if [[ "$err" != '' ]]
     then
-        echo "$err"
+        echo "$err" #todo return
         return 1
     else
         return 0
@@ -36,12 +36,12 @@ function catchStdErr() {
 }
 
 function usage() {
-    [ "$1" = "" ] || echo -e "\n\t${r}ERROR: \"$1\" is a required argument but is missing or is invalid${s}"
+    [[ "$1" = "" ]] || echo -e "\n\t${r}ERROR: \"$1\" is a required argument but is missing or is invalid${s}"
     echo -e "Usage: folder-sync start | stop [options]
 
         Options:
-        < -s | --source >  < -d | --dest >  < -u | --user >  < -p | --password >
-        [ -m | --marker ] [ -R ] [ -v ] [ -q ] [ -b ]
+        <-s | --source>  <-d | --dest>  <-u | --user>  <-p | --password>
+        [-m | --marker] [-R] [-v] [-q] [-b]
         Type 'folder-sync --help' for more information."
     exit 2
 }
@@ -74,6 +74,7 @@ function help {
         -p , --password   set the password. If omitted, the script will ask for it on the console
         -m , --marker     custom cut-off time marker
         -l , --logfile    log file
+        -L , --loglevel   specify log level from 0 to 4: (0) silent; (1) error; (3) warn; (2) info; (4) verbose
         -R                when provided will delete the file from the source location
         -O                force overwrite when file with the same name already exists
                               (by default will overwrite only when the files have same size and modify dates)
@@ -86,37 +87,38 @@ function help {
 
 # shellcheck disable=SC2034
 parseArgs() {
-    declare -n __cmdargs=$1
-    declare -n __argsmap=$2
+    declare -n cmdargs=$1
+    declare -n argsmap=$2
 
-    local flags="kOhvqRb:s:d:u:p:m:l:"
-    local ops="start,stop,help,source:,dest:,user:,password:,marker:logfile:"
+    local flags="kOhvqRb:s:d:u:p:m:l:L:"
+    local long="start,stop,help,source:,dest:,user:,password:,marker:logfile:,loglevel:"
 
-    __parsed=$(getopt -a -n folder_sync -o "$flags" --long "$ops" -- "${__cmdargs[@]}")
-    [ $? -ne 0 ] && usage
+    parsed=$(getopt -a -n folder_sync -o "$flags" --long "$long" -- "${cmdargs[@]}")
+    [[ $? -ne 0 ]] && usage
 
-    eval set -- "$__parsed"
+    eval set -- "$parsed"
     while :
     do
       case "$1" in
         # flags
-        -R ) __argsmap[REM_FILE]="y"     ; shift ;;
-        -O ) __argsmap[KEEP]="n"         ; shift ;;
-        -k ) __argsmap[KEEP]="y"         ; shift ;;
-        -v ) __argsmap[LEVEL]=3          ; shift ;;
-        -q ) __argsmap[LEVEL]=1          ; shift ;;
-        --start ) __argsmap[CMD]="START" ; shift ;;
+        -R ) argsmap[REM_FILE]="y"     ; shift ;;
+        -O ) argsmap[KEEP]="n"         ; shift ;;
+        -k ) argsmap[KEEP]="y"         ; shift ;;
+        -v ) argsmap[LEVEL]=3          ; shift ;;
+        -q ) argsmap[LEVEL]=0          ; shift ;;
+        --start ) argsmap[CMD]="START" ; shift ;;
         --stop ) stop ;;
 
         # options
         -h | --help) help ;;
-        -s | --source)   __argsmap[URL]=$2  ; shift 2 ;;
-        -d | --dest)     __argsmap[dest_dir]=$2 ; shift 2 ;;
-        -u | --user)     __argsmap[USER]=$2 ; shift 2 ;;
-        -p | --password) __argsmap[PWD]=$2  ; shift 2 ;;
-        -l | --logfile)  __argsmap[LOG]=$2  ; shift 2 ;;
-        -m | --marker)   __argsmap[MARKER]=$(date -d "$2" '+%s'); shift 2 ;;
-        -b ) __argsmap[SERVICE]=1; __argsmap[SLEEP]=$2; shift 2 ;;
+        -s | --source)   argsmap[URL]=$2     ; shift 2 ;;
+        -d | --dest)     argsmap[OUT_DIR]=$2 ; shift 2 ;;
+        -u | --user)     argsmap[USER]=$2    ; shift 2 ;;
+        -p | --password) argsmap[PWD]=$2     ; shift 2 ;;
+        -l | --logfile)  argsmap[LOG]=$2     ; shift 2 ;;
+        -L | --loglevel) argsmap[LEVEL]=$2   ; shift 2 ;;
+        -m | --marker)   argsmap[MARKER]=$(date -d "$2" '+%s'); shift 2 ;;
+        -b ) argsmap[SERVICE]=1; argsmap[SLEEP]=$2; shift 2 ;;
         --) shift; break ;;
         * ) echo "Unexpected option: $1" ; usage ;;
       esac
@@ -124,7 +126,7 @@ parseArgs() {
 }
 
 function stop {
-    if [ "$(uname)" = "Linux" ]
+    if [[ "$(uname)" = "Linux" ]]
     then
         killall -r folder-sync
     else
@@ -144,18 +146,18 @@ function clean() {
     exit 1
 }
 
-function runJob() {
-    local job_pid=$1
-    ({
-        local err
-        shift && { err="$("$@" 2>&1 1>&3 3>&-)"; } 3>&1;
-        echo "$err"
-        [ "$err" != '' ] && { echo "$err"; return 1; }
-    }  ) &
-
-    eval "$job_pid"="$!"
-    return
-}
+#function runJob() {
+#    local job_pid=$1
+#    ({
+#        local err
+#        shift && { err="$("$@" 2>&1 1>&3 3>&-)"; } 3>&1;
+#        echo "$err"
+#        [[ "$err" != '' ]] && { echo "$err"; return 1; }
+#    }  ) &
+#
+#    eval "$job_pid"="$!"
+#    return
+#}
 
 function getPassword() {
     local pwd="$1"
@@ -182,9 +184,9 @@ function getPassword() {
 
 # get the file details and parse the size
 function getSize() {
-    local _size="$(curl -u "$USER:$PWD" -qIL "$1" 2> /dev/null | awk '/Length/ {print $2}'|grep -o '[0-9]*')"
-    local _size=${_size:-1}
-    echo "$_size"
+    local size="$(curl -u "$USER:$PWD" -qIL "$1" 2> /dev/null | awk '/Length/ {print $2}'|grep -o '[0-9]*')"
+    local size=${size:-1}
+    echo "$size" #todo return
 }
 
 # takes an array reference and updates it with the file names in the given directory
@@ -201,17 +203,19 @@ function getDirectoryContent() {
 
 # returns the last modified time for the file provided in the URL
 function getSourceLastModifiedDate() {
-    local _dt=$(curl -s -I -u "$USER:$PWD" "$1" 2>&1 | awk '/Last-Modified:/ {sub("\r",""); print  $2,$3,$4,$5,$6,$7}')
-    echo "$(date -d "${_dt}" '+%s')" # convert to ms
+    local dt=$(curl -s -I -u "$USER:$PWD" "$1" 2>&1 | awk '/Last-Modified:/ {sub("\r",""); print  $2,$3,$4,$5,$6,$7}')
+    echo "$(date -d "${dt}" '+%s')" # convert to ms #todo return
 }
 
 function getTimeMarker() {
-    local _latest=$(find "$1" -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -d ' ' -f 1)
+    local latest=$(find "$1" -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -d ' ' -f 1)
 
-    if [ -z ${_latest+_} ]; then
-      echo "$(date '+%s')"
+    if [[ -z ${latest+_} ]]; then
+#      echo "$(date '+%s')"
+      printf "%s\n" "$(date '+%s')" > /dev/shm/fs #todo return
     else
-      echo "$(date -d "@$_latest" '+%s')"
+#      echo "$(date -d "@$latest" '+%s')"
+      printf "%s\n" "$(date -d "@$latest" '+%s')" > /dev/shm/fs #todo return
     fi
 }
 
@@ -226,12 +230,12 @@ function getNewFiles() {
     # shellcheck disable=SC2068
     for f in ${arr[@]}; do
         lmd=$(getSourceLastModifiedDate "$url/$f")
-        [ -n "$lmd" ] || continue
-        if [ "$cutoff" -ge "$lmd" ]; then
-            print "\t(-) $f is old - skipped"
+        [[ -n "$lmd" ]] || continue
+        if [[ "$cutoff" -ge "$lmd" ]]; then
+            echo -I "\t(-) $f is old - skipped"
             arr=("${arr[@]/$f}") # remove old file
         else
-            print "${g}\t(+) $f is newer - downloading${s}"
+            echo -W "\t(+) $f is newer - downloading"
         fi
     done
     echo
@@ -242,22 +246,22 @@ function showProgress() {
     local directory="$2"
     local file_name="$3"
     local chunks="$4"
-    local file_size="$5"
+    local filesize="$5"
     local time="$6"
     local err="$7"
 
     local kb=1024; local mb=1048576; local gb=1073741824; local units=$kb; local scale="Kb"
 
-    [[ $file_size -eq 0 ]] && return
-    [[ $file_size -ge $mb ]] && { units=$kb; scale="Kb"; }
-    [[ $file_size -ge $gb ]] && { units=$mb; scale="Mb"; }
-    [[ $file_size -gt $gb ]] && { units=$gb; scale="Gb"; }
+    [[ $filesize -eq 0 ]] && return
+    [[ $filesize -ge $mb ]] && { units=$kb; scale="Kb"; }
+    [[ $filesize -ge $gb ]] && { units=$mb; scale="Mb"; }
+    [[ $filesize -gt $gb ]] && { units=$gb; scale="Gb"; }
 
     local completed=$(( $(eval ls -l "$directory/$file_name.{1..$chunks}" 2> /dev/null | \
         awk 'BEGIN{s=0}{s+=$5}END{print s}') ))
     local elapsed=$(( $(date +%s) - time ))
     local rate=$(( ( completed / elapsed )/units ))
-    local pct=$(( ( completed*100 ) / file_size ))
+    local pct=$(( ( completed*100 ) / filesize ))
 
     local status
     if [[ $pct -lt 100 ]]; then status="${y}Downloading${s}"; else status="${g}Completed${s}"; fi
@@ -265,7 +269,7 @@ function showProgress() {
 
     printf "%-15b" "$action"
     printf "%-30s" "$file_name"
-    printf "%6s / %-6s @ %6s %3s/sec (%3s%%)" $((completed/units)) $((file_size/units)) $((rate)) $scale $pct
+    printf "%6s / %-6s @ %6s %3s/sec (%3s%%)" $((completed/units)) $((filesize/units)) $((rate)) $scale $pct
     printf "%-25b" "......$status"
     if [[ $action == 'Canceled' ]]; then printf "%40s\n" "[$err]"; fi
 }
@@ -279,8 +283,8 @@ function downloadFile() {
 
     local wrk_dir="$dest_dir/.wrk"
     mkdir -p "$wrk_dir"; chmod 755 "$wrk_dir"
-    [ -d "$wrk_dir" ] || {
-        print "ERROR: Cannot create working directory [$wrk_dir]. Please check permissions";
+    [[ -d "$wrk_dir" ]] || {
+        echo -e "ERROR: Cannot create working directory [$wrk_dir]. Please check permissions";
         exit;
     }
 
@@ -294,14 +298,14 @@ function downloadFile() {
     do
         sleep 1
         showProgress "Processing" "$wrk_dir" "$file_name" "$chunks" "$size" "$time"
-        tput ech ${#_size} # erase the last reported size value
+        tput ech ${#size} # erase the last reported size value
         tput cub 1000 # move 1000 chars left
     done
 
     read -r job_response < /dev/shm/fs # get the job actual output
     job_err=$(jobs | awk '/Exit/ {print $3}') # or another way to get just the exit code
 
-    if [ "$job_err" == '' ]; then
+    if [[ "$job_err" == '' ]]; then
         showProgress 'Processed' "$wrk_dir" "$file_name" "$chunks" "$size" "$time"
     else
         showProgress 'Canceled' "$wrk_dir" "$file_name" "$chunks" "$size" "$time" "$job_response"
@@ -311,7 +315,7 @@ function downloadFile() {
 
     # todo preserve modification date
     err_msg=$(catchStdErr moveFile "$file_name" "$wrk_dir" "$dest_dir")
-#    [ $? != 0 ] && { echo "$err_msg"; return 2; }
+#    [[ $? != 0 ]] && { echo "$err_msg"; return 2; }
 
     return 0
 }
@@ -326,9 +330,9 @@ function moveFile() {
     rm -f "$source_dir/$file_name".{1..1}
 
     # just move it if there is no name conflict
-    if  [ "$KEEP" = 'n' ] || [ ! -f "$target_dir/$file_name" ]; then
+    if  [[ "$KEEP" = 'n' ]] || [[ ! -f "$target_dir/$file_name" ]]; then
         err_msg=$(catchStdErr mv "${source_dir}/${file_name}.completed" "$target_dir/$file_name")
-        [ $? != 0 ] && { echo "$err_msg"; return 2; }
+        [[ $? != 0 ]] && { echo "$err_msg"; return 2; }
         return 0
     fi
 
@@ -337,21 +341,21 @@ function moveFile() {
 
     # if option set to 'auto' check for matching name, size, mod date and overwrite
     if (( $(stat -c%s "$source_dir/$file_name.completed") == $(stat -c%s "$target_dir/$file_name") )); then
-        local same_size=true
+        local samesize=true
     fi
 
     local new_file_date="$(date -d "$(stat "$source_dir/$file_name.completed" | awk '/Modify/ {print $2" "$3" "$4}')")"
     local curr_file_date="$(date -d "$(stat "$target_dir/$file_name" | awk '/Modify/ {print $2" "$3" "$4}')")"
-    if [ "$new_file_date" = "$curr_file_date" ] ; then
+    if [[ "$new_file_date" = "$curr_file_date" ]] ; then
         local same_date=true
     fi
 
-    if [ $same_size = "true" ] && [ $same_date = "true" ]; then overwrite=true; fi
+    if [[ $samesize = "true" ]] && [[ $same_date = "true" ]]; then overwrite=true; fi
 
     local dest_name=$file_name
 
     # if option set to 'never' generate new name
-    if [ "$KEEP" = 'y' ] || [ $overwrite = "false" ] ; then
+    if [[ "$KEEP" = 'y' ]] || [[ $overwrite = "false" ]] ; then
         local i=1
         while [[ -f "$target_dir/$dest_name" ]]; do
             dest_name="${file_name%.*}($(( i++ ))).${file_name##*.}"
@@ -360,19 +364,14 @@ function moveFile() {
 
     # move to the final destination using the new file name
     err_msg=$(catchStdErr mv "${source_dir}/${file_name}.completed" "$target_dir/$dest_name")
-    [ $? != 0 ] && { echo "$err_msg"; return 2; }
+    [[ $? != 0 ]] && { echo "$err_msg"; return 2; }
 
     return 0
 }
 
 function removeRemoteFile() {
     local filepath="/$(echo "$2" | grep / | cut -d/ -f4-)"
-    err_msg=$(catchStdErr curl --ftp-pasv -s -u "$1" "$2/" -Q "DELE $filepath/$3") 2> /dev/null
-    echo "$err_msg"
-}
-
-function print() {
-  echo -e "$1 $2"
+    curl --ftp-pasv -s -u "$1" "$2/" -Q "DELE $filepath/$3" 2> /dev/null
 }
 
 function checkAndDownload() {
@@ -381,24 +380,42 @@ function checkAndDownload() {
     local out="$3"
     local -a files
 
-    print ""
-    print "Checking location [$url] for files newer than [$(date -d @"$time")]"
+    echo -I "Checking location [$url] for files newer than [$(date -d @"$time")]"
     getDirectoryContent files "$url"
     getNewFiles files "$url" "$time"
 
     # shellcheck disable=SC2068
     # todo support for parallel download
     for f in ${files[@]}; do
-        local _size=$(getSize "$url/$f")
-        downloadFile "$url" "$out" "$f" "$_size"
-        if [ $? -ne 0 ]; then
+        local size=$(getSize "$url/$f")
+        downloadFile "$url" "$out" "$f" "$size"
+        if [[ $? -ne 0 ]]; then
             (( ERR_FLAG++))
-            echo -e "${y}Error reported when downloading file $f${s}"
-        elif  [ "$DELETE_REMOTE_FILE" = "y" ]; then
+            echo -E -e "${y}Error reported when downloading file $f${s}"
+        elif  [[ "$DELETE_REMOTE_FILE" = "y" ]]; then
             err_msg=$(removeRemoteFile "$USER:$PWD" "$url" "$f")
-            [ $? != 0 ] && { (( ERR_FLAG++)); echo -e "${y}Error reported for file $f [$err_msg]${s}"; }
+            [[ $? != 0 ]] && { (( ERR_FLAG++)); echo -E -e "Error reported for file $f [$err_msg]"; }
         fi
     done
+}
+
+# override bilt in echo to customize logging
+# if custom options are not present, normal echo behaviour will be preserved
+function echo() {
+    if [[ "$1" =~ ^(-[IDWE]) ]]; then log "$@"; else builtin echo "$@"; fi
+}
+
+function log() {
+    local severity="$1" && shift
+
+    (( $LEVEL >= 3 )) && stamp="$(date +"[%m-%d %H:%M:%S]")"
+    case $severity in
+        -D ) (( $LEVEL >= 4 )) && builtin echo -e $stamp "$@" ;; # print everything
+        -I ) (( $LEVEL >= 3 )) && builtin echo -e $stamp "$@";; # print info
+        -W ) (( $LEVEL >= 2 )) && builtin echo -e $stamp "$@" ;; # print warnings
+        -E ) (( $LEVEL >= 1 )) && builtin echo -e $stamp "${y}$@${s}" ;; # print errors
+        * )  (( $LEVEL >= 1 )) && builtin echo -e $stamp "$@" ;; # print errors by default
+    esac
 }
 
 function main {
@@ -412,8 +429,12 @@ function main {
 CMD_ARGS=("$@")
 declare -A ARGS_MAP
 parseArgs CMD_ARGS ARGS_MAP
-#for K in "${!ARGS_MAP[@]}"; do echo "[$K] : [${ARGS_MAP[$K]}]"; done
 
+# set log level
+LEVEL=${ARGS_MAP[LEVEL]:-2}
+LOG=${ARGS_MAP[LOG]:-"$OUT_directory/log.txt"}
+
+for K in "${!ARGS_MAP[@]}"; do echo -D "[$K] : [${ARGS_MAP[$K]}]"; done
 
 ###############################
 # wrap all output for logging
@@ -427,10 +448,6 @@ LOGS_ROOT=.
     export log_init=1
     exec 3>&1 4>&2
     trap 'exec 2>&4 1>&3' EXIT HUP INT QUIT RETURN
-
-    # set log level
-    LEVEL=${ARGS_MAP[LEVEL]:-2}
-    LOG=${ARGS_MAP[LOG]:-"$OUT_directory/log.txt"}
 
     [[ ! -e "${LOGS_ROOT}/.log" ]] && mkdir "${LOGS_ROOT}/.log"
 
@@ -452,9 +469,9 @@ LOGS_ROOT=.
 ERR_FLAG=0
 
 # validate required arguments
-[ ${ARGS_MAP[URL]+_} ] ||  usage "-s | --source"
-[ ${ARGS_MAP[USER]+_} ] || usage "-u | --user"
-[ ${ARGS_MAP[dest_dir]+_} ] || usage "-d | --dest"
+[[ ${ARGS_MAP[URL]+_} ]] ||  usage "-s | --source"
+[[ ${ARGS_MAP[USER]+_} ]] || usage "-u | --user"
+[[ ${ARGS_MAP[OUT_DIR]+_} ]] || usage "-d | --dest"
 
 URL="${ARGS_MAP[URL]}"
 USER="${ARGS_MAP[USER]}"
@@ -463,16 +480,19 @@ KEEP=${ARGS_MAP[KEEP]:-"a"} # yes / no  / only same size & date
 CMD=${ARGS_MAP[CMD]:-"START"}
 
 # validate destination
-OUT_directory=${ARGS_MAP[dest_dir]}
-if [ ! -d "$OUT_directory" ]; then mkdir -p 755 "$OUT_directory"; chmod 0755 "$OUT_directory"; fi
-[ -d "$OUT_directory" ] || usage "-d | --dest"
+OUT_DIR=${ARGS_MAP[OUT_DIR]}
+if [[ ! -d "$OUT_DIR" ]]; then mkdir -p 755 "$OUT_DIR"; chmod 0755 "$OUT_DIR"; fi
+[[ -d "$OUT_DIR" ]] || usage "-d | --dest"
 
-# use the provided time marker, _latest timestamp in the destination directory or current time (in this order)
-CUT_OFF_TIME=${ARGS_MAP[MARKER]:-$(getTimeMarker "$OUT_directory")}
+# use the provided time marker, latest timestamp in the destination directory or current time (in this order)
+#CUT_OFF_TIME=${ARGS_MAP[MARKER]:-$(getTimeMarker "$OUT_DIR")}
+getTimeMarker "$OUT_DIR"
+read -r tm < /dev/shm/fs
+CUT_OFF_TIME=${ARGS_MAP[MARKER]:-$tm}
 
 # verify password
 PWD="${ARGS_MAP[PWD]}"
-[ -n "$PWD" ] || getPassword PWD
+[[ -n "$PWD" ]] || getPassword PWD
 
 # set service options
 SERVICE=${ARGS_MAP[SERVICE]:-0}
@@ -481,21 +501,22 @@ SLEEP=${ARGS_MAP[SLEEP]:-60}
 # ansi colors
 r='\033[1;31m' ; g='\033[1;32m'; y='\033[1;33m'; s='\033[0;37m'
 
-# todo: option for silent
-# logo
-echo -e ""
-echo -e "${g}     ____     __   __       ${y} ____             ${s}"
-echo -e "${g}    / __/__  / /__/ /__ ____${y}/ __/_ _____  ____${s}"
-echo -e "${g}   / _// _ \/ / _  / -_) __/${y}\ \/ // / _ \/ __/${s}"
-echo -e "${g}  /_/  \___/_/\_,_/\__/_/ ${y}/___/\_, /_//_/\__/ ${s}"
-echo -e "${g}                          ${y}    /___/           ${s}"
-echo -e ""
+read -r -d '' LOGO <<- EOM
+    \n
+    ${g}   ____     __   __       ${y}   ____             ${s}
+    ${g}  / __/__  / /__/ /__ ____${y}  / __/_ _____  ____${s}
+    ${g} / _// _ \/ / _  / -_) __/${y}  \ \/ // / _ \/ __/${s}
+    ${g}/_/  \___/_/\_,_/\__/_/   ${y}/___/\_, /_//_/\__/ ${s}
+    ${g}                          ${y}    /___/           ${s}
+EOM
+
+echo -E "$LOGO"
 
 # shellcheck disable=SC2031
 # shellcheck disable=SC2030
-if [ "$SERVICE" -eq 1 ]
+if [[ "$SERVICE" -eq 1 ]]
 then
-    echo -e "${g}Folder-sync started as background process; use '--stop' option to terminate it.${s}"
+    echo -I -e "${g}Folder-sync started as background process; use '--stop' option to terminate it.${s}"
     { (
         while /bin/true; do
         checkAndDownload "$URL" "$CUT_OFF_TIME" "$OUT_directory"
@@ -505,13 +526,13 @@ then
 #    done >>"$LOG" 2>&1 &
     done &); } 2>&1
 else
-    echo -e "${g}Folder-sync running...${s}"
+    echo -I -e "${g}Folder-sync running...${s}"
     checkAndDownload "$URL" "$CUT_OFF_TIME" "$OUT_directory"
-    if [ $ERR_FLAG -eq 0 ]
+    if [[ $ERR_FLAG -eq 0 ]]
     then
-        echo -e "${g}Folder-sync completed${s}"
+        echo -I -e "${g}Folder-sync completed${s}"
     else
-        echo -e "${y}Folder-sync completed with errors${s}"
+        echo -I -e "${y}Folder-sync completed with errors${s}"
     fi
-#    rm -Rf "$OUT_directory/.wrk"
+    rm -Rf "$OUT_directory/.wrk"
 fi
