add cygwin specific functions

diff --git a/folder-sync b/folder-sync
--- a/folder-sync
+++ b/folder-sync
@@ -1,6 +1,5 @@
 #!/bin/bash
-
-
+#set -e
 
 #     ____     __   __        ____
 #    / __/__  / /__/ /__ ____/ __/_ _____  ____
@@ -13,8 +12,8 @@
 # functions
 ###########################
 
+# shellcheck disable=SC2034
 # for (( i = 30; i < 38; i++ )); do echo -e "\033[0;"$i"m Normal: (0;$i); \033[1;"$i"m Light: (1;$i)"; done
-
 ansi_red='\033[1;31m'
 ansi_grn='\033[1;32m'
 ansi_yel='\033[1;33m'
@@ -22,6 +21,30 @@ ansi_blu='\033[1;34m'
 ansi_cyn='\033[1;35m'
 ansi_bl2='\033[1;36m'
 ansi_std='\033[0;37m'
+
+#trap "error reported  ${LINENO}" ERR
+exec 3>&1 4>&2 #set up extra file descriptors
+
+#{ ERR_MSG="$( { mv "${WRK_DIR}/${NAME}.2" "$DEST/$NAME"; } 2>&1 1>&3 3>&- )"; } 3>&1;
+function catch-stderr() {
+    local -n v="$1";
+    shift && { v="$("$@" 2>&1 1>&3 3>&-)"; } 3>&1;
+}
+
+function catch-stderr2() {
+    local err=''
+    { err="$("$@" 2>&1 1>&3 3>&-)"; } 3>&1
+
+    if [ "$err" != '' ]
+    then
+        echo "$err"
+        return 1
+    else
+        return 0
+    fi
+}
+
+
 
 function usage() {
     [ "$1" = "" ] || echo -e "\n\t${ansi_red}ERROR: \"$1\" is a required argument but is missing or is invalid${ansi_std}"
@@ -69,6 +92,7 @@ function help {
   exit 0
 }
 
+# shellcheck disable=SC2034
 parseArgs() {
     declare -n __cmdargs=$1
     declare -n __argsmap=$2
@@ -100,7 +124,7 @@ parseArgs() {
         -p | --password) __argsmap[PWD]=$2  ; shift 2 ;;
         -l | --logfile)  __argsmap[LOG]=$2  ; shift 2 ;;
         -b ) __argsmap[SERVICE]=1; __argsmap[SLEEP]=$2; shift 2 ;;
-        -m | --marker)   __argsmap[MARKER]=$(date -d "@$2" '+%s'); shift 2 ;;
+        -m | --marker)   __argsmap[MARKER]=$(date -d "$2" '+%s'); shift 2 ;;
         --) shift; break ;;
         *) echo "Unexpected option: $1" ; usage ;;
       esac
@@ -121,11 +145,11 @@ function stop {
 }
 
 #Cleanup on kill
-function clean {
-  print "${ansi_red}Download failed! Cleaning...${ansi_std}"
-  kill 0
-  rm -Rf "$OUT_DIR/wrk"
-  exit 1
+function clean() {
+    echo -e "${ansi_red}Download failed!${ansi_std} ERROR is [$1]"
+    kill 0
+    rm -Rf "$OUT_DIR/wrk"
+    exit 1
 }
 
 function getPassword() {
@@ -155,10 +179,6 @@ function getPassword() {
     return
 }
 
-
-
-
-
 # get the file details and parse the size
 function getSize() {
     local __size
@@ -179,16 +199,17 @@ function getDirectoryContent() {
     return
 }
 
-# takes the complete URL as argument and returns the last modified time
+# returns the last modified time for the file provided in the URL
 function getSourceLastModifiedDate() {
-    local dt=$(curl -I -u "$USER:$PWD" "$1" 2>&1 | awk '/Last-Modified:/ {sub("\r",""); print  $2,$3,$4,$5,$6,$7}')
-    local ms="$(date -d "${dt}" '+%s')" # convert to ms
-    echo "$ms"
+    local dt
+    dt=$(curl -I -u "$USER:$PWD" "$1" 2>&1 | awk '/Last-Modified:/ {sub("\r",""); print  $2,$3,$4,$5,$6,$7}')
+    echo "$(date -d "${dt}" '+%s')" # convert to ms
     return
 }
 
 function getTimeMarker() {
-    local latest=$(find "$1" -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -d ' ' -f 1)
+    local latest
+    latest=$(find "$1" -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -d ' ' -f 1)
 
     if [ -z ${latest+_} ]; then
       echo "$(date '+%s')"
@@ -223,26 +244,39 @@ function getNewFiles() {
     return
 }
 
+# shellcheck disable=SC2086
+# shellcheck disable=SC2175
 function calcProgress() {
-        # local FNAME=$1
-        # local PARTNUM=$2
-        # local SZ=$3
-        # local T=$4
+        local action="$1"
+        local DIR="$2"
+        local FILE_NAME="$3"
+        local CHUNKS="$4"
+        local FILE_SIZE="$5"
+        local TIME="$6"
 
-        [[ $3 -eq 0 ]] && return
+        local b=1
+        local kb=1024
+        local mb=1048576
+        local gb=1073741824
+        local units=$kb
+        local scale="Kb"
 
-        local GOT__size=$((`eval ls -l "$1".{1..$2} 2> /dev/null | awk 'BEGIN{SUM=0}{SUM=SUM+$5}END{print SUM}'`))
-        local TIMEDIFF=$(( `date +%s` - $4 ))
-        local RATE=$(( ($GOT__size / $TIMEDIFF)/1024 ))
-        local PCT=$(( ($GOT__size*100) / $3 ))
+        [[ $FILE_SIZE -eq 0 ]] && return
+        [[ $FILE_SIZE -ge $mb ]] && { units=$kb; scale="Kb"; }
+        [[ $FILE_SIZE -ge $gb ]] && { units=$mb; scale="Mb"; }
+        [[ $FILE_SIZE -gt $gb ]] && { units=$gb; scale="Gb"; }
 
-        echo  "Downloading $1 in $2 parts: $(($GOT__size/1048576)) / $(($3/1048576)) mb @ $(($RATE)) KB/s ($PCT%).    "
-#        local progress_msg
-#        progress_msg="Downloading $1 in $2 parts: $(($GOT__size/1048576)) / $(($3/1048576)) mb @ $(($RATE)) KB/s ($PCT%).    "
-#        echo "$progress_msg"
+        local COMPLETED=$(( $(eval ls -l $DIR/$FILE_NAME.{1..$CHUNKS} 2> /dev/null | awk 'BEGIN{SUM=0}{SUM=SUM+$5}END{print SUM}') ))
+        local ELAPSED=$(( $(date +%s) - TIME ))
+        local RATE=$(( ( COMPLETED / ELAPSED )/units ))
+        local PCT=$(( ( COMPLETED*100 ) / FILE_SIZE ))
+        local STATUS
+        if [[ $PCT -lt 100 ]]; then STATUS="...${ansi_yel}Downloading${ansi_std}"; else STATUS="...${ansi_grn}Completed${ansi_std}"; fi
+
+        local msg="$action $FILE_NAME in $CHUNKS part(s): $((COMPLETED/units)) / $((FILE_SIZE/units)) $scale @ $((RATE)) $scale/s ($PCT%).......$STATUS"
+        echo -en "$msg"
 #        tput ech ${#__size} # erase the last reported size value
 #        tput cub 1000 # move 1000 chars left
-
   return
 }
 
@@ -250,38 +284,38 @@ function download() {
     local SRC="$1"
     local DEST="$2"
     local NAME="$3"
-    local __size=$4
+    local size="$4"
     local SPLIT_NUM=1 # only needed when downloading in multiple parts
 
     WRK_DIR="$DEST/wrk"
     mkdir -p "$WRK_DIR" ; chmod 755 "$WRK_DIR"
     [ -d "$OUT_DIR" ] || print "ERROR: Cannot create working directory [$WRK_DIR]. Please check destination permissions"
 
-    curl -R --ftp-pasv -u "$USER:$PWD" -o "${WRK_DIR}/${NAME}.1" "$SRC/$NAME" 2> /dev/null &
+    curl -R --ftp-pasv -u "$USER:$PWD+" -o "${WRK_DIR}/${NAME}.1" "$SRC/$NAME" 2> /dev/null &
+#    [ $? -ne 0 ] && clean "$ERR_MSG"
+
+#    echo "Job details: $(jobs -x)"
 
     # Wait for the job to complete while showing progress
     TIME=$(( $(date +%s)-1 ))
+    echo
     while jobs | grep -q Running ;
     do
-#        echo -n "$(calcProgress "${WRK_DIR}/${NAME}.1" "$SPLIT_NUM" "$__size" "$TIME")"
-#        tput ech ${#__size} # erase the last reported size value
-#        tput cub 1000 # move 1000 chars left
         sleep 1
+        calcProgress "Downloading" "$WRK_DIR" "$NAME" "$SPLIT_NUM" "$size" "$TIME"
+        tput ech ${#__size} # erase the last reported size value
+        tput cub 1000 # move 1000 chars left
     done
 
-#    echo "$(calcProgress "${WRK_DIR}/${NAME}.1" "$SPLIT_NUM" "$__size ""$TIME")"
+    calcProgress "Completed"  "$WRK_DIR" "$NAME" "$SPLIT_NUM" "$size" "$TIME"
+    echo
+    echo "Job $(jobs)"
 
-    mv "${WRK_DIR}/${NAME}.1" "$DEST/$NAME"
+    ERR_MSG=$(catch-stderr2 mv "${WRK_DIR}/${NAME}.1" "$DEST/$NAME")
 
-    if [ $? -eq 0 ]
-    then
-        local file_path
-        file_path=$(echo "$SRC" | cut -d@ -f2 | cut -d/ -f2- | cut -d? -f1)
-        [ "$DELETE_REMOTE_FILE" = "y" ] && curl -u "$USER:$PWD" "$SRC" -Q"DELE $file_path/$NAME" 2> /dev/null
-    else
-        echo "Could not download file: $?" >&2
-        clean
-    fi
+    [ $? -ne 0 ] && clean "$ERR_MSG"
+
+    [ "$DELETE_REMOTE_FILE" = "y" ]  && curl -u "$USER:$PWD" "$SRC" -Q"DELE $file_path/$NAME" 2> /dev/null
 }
 
 function print() {
@@ -301,10 +335,10 @@ function checkAndDownload() {
 #    print "New files to download: " "$(( ${#files[@]}-1 ))"
 
     # shellcheck disable=SC2068
+    # shellcheck disable=SC2155
     for f in ${files[@]}; do
-        local __size=$(getSize "$__url/$f")
-        echo "Downloading $f with size $__size"
-        download "$__url" "$__out" "$f" "$__size"
+        local _size=$(getSize "$__url/$f")
+        download "$__url" "$__out" "$f" "$_size"
     done
 
     return
@@ -321,7 +355,7 @@ declare -A ARGS_MAP
 parseArgs CMD_ARGS ARGS_MAP
 
 #todo verbose option
-#for K in "${!ARGS_MAP[@]}"; do echo "[$K] : [${ARGS_MAP[$K]}]"; done
+for K in "${!ARGS_MAP[@]}"; do echo "[$K] : [${ARGS_MAP[$K]}]"; done
 
 # validate required arguments
 [ ${ARGS_MAP[URL]+_} ] ||  usage "-s | --source"
@@ -365,8 +399,8 @@ LOG=${ARGS_MAP[LOG]:-"$OUT_DIR/log.txt"}
 #print "CUT_OFF_TIME" "$(date -d "@$CUT_OFF_TIME")"
 
 ## set trap commands
-trap clean SIGINT SIGTERM
-trap "exit" INT TERM ERR
+#trap clean SIGINT SIGTERM
+#trap "exit" INT TERM ERR
 #trap "kill 0" EXIT # terminated all jobs on exit
 
 
@@ -380,6 +414,8 @@ echo -e "${ansi_grn}  /_/  \___/_/\_,_/\__/_/ ${ansi_yel}/___/\_, /_//_/\__/ ${a
 echo -e "${ansi_grn}                          ${ansi_yel}    /___/           ${ansi_std}"
 echo -e ""
 
+# shellcheck disable=SC2031
+# shellcheck disable=SC2030
 if [ "$SERVICE" -eq 1 ]
 then
     echo -e "${ansi_grn}Folder-sync started as background process; use '--stop' option to terminate it.${ansi_std}"
@@ -387,6 +423,7 @@ then
         while /bin/true; do
         checkAndDownload "$URL" "$CUT_OFF_TIME" "$OUT_DIR"
         sleep "$SLEEP"
+
         CUT_OFF_TIME=$(getTimeMarker "$OUT_DIR") #update time marker
 #    done 2>&1>>"$LOG" &
     done &); }  2>&1>>"$LOG"
