use shared memory for the curl jobs IPC

diff --git a/folder-sync b/folder-sync
--- a/folder-sync
+++ b/folder-sync
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-(set -o igncr) 2>/dev/null && set -o igncr; # cygwin specific shell options
+#(set -o igncr) 2>/dev/null && set -o igncr; # cygwin specific shell options
 #set -e
 #set -x
 
@@ -17,13 +17,13 @@
 
 # shellcheck disable=SC2034
 # for (( i = 30; i < 38; i++ )); do echo -e "\033[0;"$i"m Normal: (0;$i); \033[1;"$i"m Light: (1;$i)"; done
-ansi_red='\033[1;31m'
-ansi_grn='\033[1;32m'
-ansi_yel='\033[1;33m'
-ansi_blu='\033[1;34m'
-ansi_cyn='\033[1;35m'
-ansi_bl2='\033[1;36m'
-ansi_std='\033[0;37m'
+r='\033[1;31m'
+g='\033[1;32m'
+y='\033[1;33m'
+b='\033[1;34m'
+c='\033[1;35m'
+b2='\033[1;36m'
+s='\033[0;37m'
 
 #exec 3>&1 4>&2 #set up extra file descriptors
 function catch-stderr() {
@@ -46,7 +46,7 @@ function catch-stderr2() {
 }
 
 function usage() {
-    [ "$1" = "" ] || echo -e "\n\t${ansi_red}ERROR: \"$1\" is a required argument but is missing or is invalid${ansi_std}"
+    [ "$1" = "" ] || echo -e "\n\t${r}ERROR: \"$1\" is a required argument but is missing or is invalid${s}"
     echo -e "Usage: folder-sync start | stop [options]
 
         Options:
@@ -57,17 +57,17 @@ function usage() {
 }
 
 function help {
-   echo -e "${ansi_std}
-    Monitors an FTP directory and downloads all new files as per the provided options.
+   echo -e "${s}
+    Monitors an FTP directory and downloads all new _files as per the provided options.
 
-    Note that there are three options for identifying \"new\" files:
+    Note that there are three options for identifying \"new\" _files:
         1. Any file newer that the last file downloaded in the destination directory
-        2. Any file newer than the script start time if there are no files in the destination directory
+        2. Any file newer than the script start time if there are no _files in the destination directory
         3. Any file newer than the time marker provided with the -m option e.g. -m \"yesterday\"
             see GNU documentation for all accepted formats:
             https://www.gnu.org/software/coreutils/manual/html_node/Date-input-formats.html#Date-input-formats
 
-    To continuously download new files, use the -b option
+    To continuously download new _files, use the -b option
 
     Usage:
 
@@ -76,7 +76,7 @@ function help {
         stop    stop the background process (applicable only for -b option)
 
     Required:
-        -s , --source     set the FTP source URL (with port if not using 21) along with the path i.e. \"ftp://192.168.1.1/ftp/root/files\"
+        -s , --source     set the FTP source URL (with port if not using 21) along with the path i.e. \"ftp://192.168.1.1/ftp/root/_files\"
         -d , --dest       set the destination directory
         -u , --user       set user name
 
@@ -143,10 +143,23 @@ function stop {
 
 #Cleanup on kill
 function clean() {
-    echo -e "${ansi_red}Download failed!${ansi_std} ERROR is [$1]"
+    echo -e "${r}Download failed!${s} ERROR is [$1]"
     kill 0
-    rm -Rf "$OUT_DIR/wrk"
+    rm -Rf "$OUT_directory/wrk"
     exit 1
+}
+
+function runJob() {
+    local job_pid=$1
+    ({
+        local err
+        shift && { err="$("$@" 2>&1 1>&3 3>&-)"; } 3>&1;
+        echo "$err"
+        [ "$err" != '' ] && { echo "$err"; return 1; }
+    }  ) &
+
+    eval "$job_pid"="$!"
+    return
 }
 
 function getPassword() {
@@ -178,60 +191,59 @@ function getPassword() {
 
 # get the file details and parse the size
 function getSize() {
-    local __size
-    __size="$(curl -u "$USER:$PWD" -qIL "$1" 2> /dev/null | awk '/Length/ {print $2}'|grep -o '[0-9]*')"
-    local __size=${__size:-1}
-    echo "$__size"
+    local _size="$(curl -u "$USER:$PWD" -qIL "$1" 2> /dev/null | awk '/Length/ {print $2}'|grep -o '[0-9]*')"
+    local _size=${_size:-1}
+    echo "$_size"
     return
 }
 
-# takes an array reference and updates it with the file names in the given directory
+# takes an _array reference and updates it with the file names in the given directory
 function getDirectoryContent() {
-    local -n arr=$1
-    local url="$2"
+    local -n _arr=$1
+    local _url="$2"
 
+    #todo error checking & reporting
     # shellcheck disable=SC2034
-    arr=("$(curl -s -u "$USER:$PWD" "$url/" | sed -nr 's/(^-[ rw-].*)( *)([0-9])(.*)/\4/p' | sed -e 's/^ //g' | sed -e 's/ /\ /g')")
+    _arr=("$(curl -s -u "$USER:$PWD" "$_url/" | sed -nr 's/(^-[ rw-].*)( *)([0-9])(.*)/\4/p' | sed -e 's/^ //g' | sed -e 's/ /\ /g')")
 
     return
 }
 
 # returns the last modified time for the file provided in the URL
 function getSourceLastModifiedDate() {
-    local dt
-    dt=$(curl -s -I -u "$USER:$PWD" "$1" 2>&1 | awk '/Last-Modified:/ {sub("\r",""); print  $2,$3,$4,$5,$6,$7}')
-    echo "$(date -d "${dt}" '+%s')" # convert to ms
+    local _dt=$(curl -s -I -u "$USER:$PWD" "$1" 2>&1 | awk '/Last-Modified:/ {sub("\r",""); print  $2,$3,$4,$5,$6,$7}')
+    echo "$(date -d "${_dt}" '+%s')" # convert to ms
     return
 }
 
 function getTimeMarker() {
-    local latest
-    latest=$(find "$1" -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -d ' ' -f 1)
+    local _latest=$(find "$1" -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -d ' ' -f 1)
 
-    if [ -z ${latest+_} ]; then
+    if [ -z ${_latest+_} ]; then
       echo "$(date '+%s')"
     else
-      echo "$(date -d "@$latest" '+%s')"
+      echo "$(date -d "@$_latest" '+%s')"
     fi
 
     return
 }
 
-# filters out any files that are older than the cutoff time
+# filters out any _files that are older than the _cutoff time
 function getNewFiles() {
-    local -n __arr=$1
-    local url=$2
-    local cutoff=$3
-    local lmd
+    # shellcheck disable=SC2178
+    local -n _arr=$1
+    local _url=$2
+    local _cutoff=$3
+    local _lmd
 
     # shellcheck disable=SC2068
-    for f in ${__arr[@]}; do
+    for f in ${_arr[@]}; do
         # echo "f: [$f]" # todo check file is not empty
-        lmd=$(getSourceLastModifiedDate "$url/$f") #todo verify lmd is not empty
-        [ -n "$lmd" ] || continue
-        if [ "$cutoff" -ge "$lmd" ]; then
+        _lmd=$(getSourceLastModifiedDate "$_url/$f") #todo verify _lmd is not empty
+        [ -n "$_lmd" ] || continue
+        if [ "$_cutoff" -ge "$_lmd" ]; then
             print "\t(-) $f is old - skipped"
-            __arr=("${__arr[@]/$f}") # remove old file
+            _arr=("${_arr[@]/$f}") # remove old file
         else
           print "(+) $f is newer - downloading"
         fi
@@ -240,59 +252,41 @@ function getNewFiles() {
     return
 }
 
-# shellcheck disable=SC2086
-# shellcheck disable=SC2175
-function calcProgress() {
-        local action="$1"
-        local DIR="$2"
-        local FILE_NAME="$3"
-        local CHUNKS="$4"
-        local FILE_SIZE="$5"
-        local TIME="$6"
+function showProgress() {
+    local action="$1"
+    local directory="$2"
+    local file_name="$3"
+    local chunks="$4"
+    local file_size="$5"
+    local time="$6"
+    local err="$7"
 
-        local b=1
-        local kb=1024
-        local mb=1048576
-        local gb=1073741824
-        local units=$kb
-        local scale="Kb"
+    local b=1
+    local kb=1024
+    local mb=1048576
+    local gb=1073741824
+    local units=$kb
+    local scale="Kb"
 
-        [[ $FILE_SIZE -eq 0 ]] && return
-        [[ $FILE_SIZE -ge $mb ]] && { units=$kb; scale="Kb"; }
-        [[ $FILE_SIZE -ge $gb ]] && { units=$mb; scale="Mb"; }
-        [[ $FILE_SIZE -gt $gb ]] && { units=$gb; scale="Gb"; }
+    [[ $file_size -eq 0 ]] && return
+    [[ $file_size -ge $mb ]] && { units=$kb; scale="Kb"; }
+    [[ $file_size -ge $gb ]] && { units=$mb; scale="Mb"; }
+    [[ $file_size -gt $gb ]] && { units=$gb; scale="Gb"; }
 
-        local COMPLETED=$(( $(eval ls -l $DIR/$FILE_NAME.{1..$CHUNKS} 2> /dev/null | awk 'BEGIN{SUM=0}{SUM=SUM+$5}END{print SUM}') ))
-        local ELAPSED=$(( $(date +%s) - TIME ))
-        local RATE=$(( ( COMPLETED / ELAPSED )/units ))
-        local PCT=$(( ( COMPLETED*100 ) / FILE_SIZE ))
+    local completed=$(( $(eval ls -l "$directory/$file_name.{1..$chunks}" 2> /dev/null | awk 'BEGIN{s=0}{s+=$5}END{print s}') ))
+    local elapsed=$(( $(date +%s) - time ))
+    local rate=$(( ( completed / elapsed )/units ))
+    local pct=$(( ( completed*100 ) / file_size ))
 
-        local STATUS
-        if [[ $PCT -lt 100 ]]; then STATUS="......${ansi_yel}Downloading${ansi_std}"; else STATUS="......${ansi_grn}Completed${ansi_std}"; fi
-        if [[ $action == 'Canceled' ]]; then STATUS="......${ansi_red}FAILED${ansi_std}"; fi
+    local status
+    if [[ $pct -lt 100 ]]; then status="${y}Downloading${s}"; else status="${g}Completed${s}"; fi
+    if [[ $action == 'Canceled' ]]; then status="${r}FAILED${s}"; fi
 
-#        local msg="$action $FILE_NAME: $((COMPLETED/units)) / $((FILE_SIZE/units)) $scale @ $((RATE)) $scale/s ($PCT%).......$STATUS           "
-#        echo -en "$msg"
-
-        printf  "%-15b" $action
-        printf "%-30s" $FILE_NAME
-        printf "%6s / %-6s %2s @ %6s %3s/cek (%3s%%)" $((COMPLETED/units)) $((FILE_SIZE/units)) $scale $((RATE)) $scale $PCT
-        printf "%-25b           " $STATUS
-
-  return
-}
-
-function runJob() {
-    local job_pid=$1
-    ({
-        local _err
-        shift && { _err="$("$@" 2>&1 1>&3 3>&-)"; } 3>&1;
-        echo "$_err"
-        [ "$_err" != '' ] && { echo "$_err"; return 1; }
-    }  ) &
-
-    eval "$job_pid"="$!"
-    return
+    printf  "%-15b" "$action"
+    printf "%-30s" "$file_name"
+    printf "%6s / %-6s %2s @ %6s %3s/cek (%3s%%)" $((completed/units)) $((file_size/units)) $scale $((rate)) $scale $pct
+    printf "%-25b" "......$status"
+    if [[ $action == 'Canceled' ]]; then printf "%40s" "[$err]"; fi
 }
 
 function download() {
@@ -302,35 +296,43 @@ function download() {
     local size="$4"
     local SPLIT_NUM=1 # only needed when downloading in multiple parts
 
-    WRK_DIR="$DEST/wrk"
-    mkdir -p "$WRK_DIR" ; chmod 755 "$WRK_DIR"
-    [ -d "$OUT_DIR" ] || { print "ERROR: Cannot create working directory [$WRK_DIR]. Please check permissions"; exit; }
+    WRK_directory="$DEST/wrk"
+    mkdir -p "$WRK_directory" ; chmod 755 "$WRK_directory"
+    [ -d "$OUT_directory" ] || { print "ERROR: Cannot create working directory [$WRK_directory]. Please check permissions"; exit; }
 
-    # [[ $NAME == 'BCDriverMerge.exe' ]] && NAME=' BCDriverMerge.exe' # just for testing
-    # { read readit < <(curl --write-out "%{http_code}\n" -sS -R --ftp-pasv -u "$USER:$PWD" -o "${WRK_DIR}/${NAME}.1" "$SRC/$NAME" 2>&1); echo "read [$readit]"; } &
-    curl -s -R --ftp-pasv -u "$USER:$PWD" -o "${WRK_DIR}/${NAME}.1" "$SRC/$NAME" >/dev/null 2>&1 &
+    # [[ $NAME == 'BCDriverMerge.exe' ]] && NAME='*BCDriverMerge.exe' # just for testing
+    # curl --write-out "%{http_code}\n" -sS -R --ftp-pasv -u "$USER:$PWD" -o "${WRK_directory}/${NAME}.1" "$SRC/$NAME" >/dev/shm/fs 2>&1 &
+    curl -sS -R --ftp-pasv -u "$USER:$PWD" -o "${WRK_directory}/${NAME}.1" "$SRC/$NAME" >/dev/shm/fs 2>&1 &
 
     # Wait for the job to complete while showing progress
-    TIME=$(( $(date +%s)-1 ))
+    time=$(( $(date +%s)-1 ))
     while jobs | grep -q Running ;
     do
         sleep 1
-        calcProgress "Processing" "$WRK_DIR" "$NAME" "$SPLIT_NUM" "$size" "$TIME"
-        tput ech ${#__size} # erase the last reported size value
+        showProgress "Processing" "$WRK_directory" "$NAME" "$SPLIT_NUM" "$size" "$time"
+        tput ech ${#_size} # erase the last reported size value
         tput cub 1000 # move 1000 chars left
     done
 
-    job_err=$(jobs | awk '/Exit/ {print $3}')
-    if [ "$job_err" == '' ]; then action='Processed'; else action='Canceled'; ((ERR++)); fi
-    calcProgress "$action" "$WRK_DIR" "$NAME" "$SPLIT_NUM" "$size" "$TIME"
+
+    read -r job_response < /dev/shm/fs # get the job actual output
+    job_err=$(jobs | awk '/Exit/ {print $3}') # or another way to get just the exit code
+
+    if [ "$job_err" == '' ]
+    then
+        showProgress 'Processed' "$WRK_directory" "$NAME" "$SPLIT_NUM" "$size" "$time"
+    else
+        showProgress 'Canceled' "$WRK_directory" "$NAME" "$SPLIT_NUM" "$size" "$time" "$job_response"
+        ((ERR++))
+    fi
     echo
 
-    mv "$WRK_DIR/$NAME.1" "$DEST/$NAME" 2> /dev/null
-#    ERR_MSG=$(catch-stderr2 mv "${WRK_DIR}/${NAME}.1" "$DEST/$NAME")
+    ERR_MSG=$(catch-stderr2 mv "${WRK_directory}/${NAME}.1" "$DEST/$NAME")
+    [ $? -ne 0 ] && [ "$job_response" == '' ] && { print "$ERR_MSG"; ((ERR++)); }
 
-#    [ $? -ne 0 ] && clean "$ERR_MSG"
+    [ "$DELETE_REMOTE_FILE" = "y" ] && curl -u "$USER:$PWD" "$SRC" -Q"DELETE $SRC/$NAME" 2> /dev/null
 
-    [ "$DELETE_REMOTE_FILE" = "y" ]  && curl -u "$USER:$PWD" "$SRC" -Q"DELETE $SRC/$NAME" 2> /dev/null
+    return "$ERR"
 }
 
 function print() {
@@ -338,21 +340,20 @@ function print() {
 }
 
 function checkAndDownload() {
-    local __url="$1"
-    local __time="$2"
-    local __out="$3"
-    local -a files
+    local _url="$1"
+    local _time="$2"
+    local _out="$3"
+    local -a _files
 
     print ""
-    print "Checking for new files as off [$(date -d @"$__time")] in [$__url]"
-    getDirectoryContent files "$__url"
-    getNewFiles files "$__url" "$__time"
+    print "Checking for new files as off [$(date -d @"$_time")] in [$_url]"
+    getDirectoryContent _files "$_url"
+    getNewFiles _files "$_url" "$_time"
 
     # shellcheck disable=SC2068
-    # shellcheck disable=SC2155
-    for f in ${files[@]}; do
-        local _size=$(getSize "$__url/$f")
-        download "$__url" "$__out" "$f" "$_size"
+    for f in ${_files[@]}; do
+        local _size=$(getSize "$_url/$f")
+        download "$_url" "$_out" "$f" "$_size"
     done
 
     return
@@ -386,12 +387,12 @@ DELETE_REMOTE_FILE=${ARGS_MAP[REM_FILE]:-"n"}
 CMD=${ARGS_MAP[CMD]:-"START"}
 
 # validate destination
-OUT_DIR=${ARGS_MAP[DEST]}
-if [ ! -d "$OUT_DIR" ]; then mkdir -p 755 "$OUT_DIR"; chmod 0755 "$OUT_DIR"; fi
-[ -d "$OUT_DIR" ] || usage "-d | --dest"
+OUT_directory=${ARGS_MAP[DEST]}
+if [ ! -d "$OUT_directory" ]; then mkdir -p 755 "$OUT_directory"; chmod 0755 "$OUT_directory"; fi
+[ -d "$OUT_directory" ] || usage "-d | --dest"
 
-# use the provided time marker, latest timestamp in the destination directory or current time (in this order)
-CUT_OFF_TIME=${ARGS_MAP[MARKER]:-$(getTimeMarker "$OUT_DIR")}
+# use the provided time marker, _latest timestamp in the destination directory or current time (in this order)
+CUT_OFF_TIME=${ARGS_MAP[MARKER]:-$(getTimeMarker "$OUT_directory")}
 
 # verify password
 PWD="${ARGS_MAP[PWD]}"
@@ -403,11 +404,11 @@ SLEEP=${ARGS_MAP[SLEEP]:-60}
 
 # set log level
 LEVEL=${ARGS_MAP[LEVEL]:-2}
-LOG=${ARGS_MAP[LOG]:-"$OUT_DIR/log.txt"}
+LOG=${ARGS_MAP[LOG]:-"$OUT_directory/log.txt"}
 
 # todo: add verbose mode
 #print "URL" "$URL"
-#print "OUT_DIR" "$OUT_DIR"
+#print "OUT_directory" "$OUT_directory"
 #print "USER" "$USER"
 #print "SERVICE" "$SERVICE"
 #print "SLEEP" "$SLEEP"
@@ -425,36 +426,36 @@ LOG=${ARGS_MAP[LOG]:-"$OUT_DIR/log.txt"}
 # logo
 # todo: option for silent
 echo -e ""
-echo -e "${ansi_grn}     ____     __   __       ${ansi_yel} ____             ${ansi_std}"
-echo -e "${ansi_grn}    / __/__  / /__/ /__ ____${ansi_yel}/ __/_ _____  ____${ansi_std}"
-echo -e "${ansi_grn}   / _// _ \/ / _  / -_) __/${ansi_yel}\ \/ // / _ \/ __/${ansi_std}"
-echo -e "${ansi_grn}  /_/  \___/_/\_,_/\__/_/ ${ansi_yel}/___/\_, /_//_/\__/ ${ansi_std}"
-echo -e "${ansi_grn}                          ${ansi_yel}    /___/           ${ansi_std}"
+echo -e "${g}     ____     __   __       ${y} ____             ${s}"
+echo -e "${g}    / __/__  / /__/ /__ ____${y}/ __/_ _____  ____${s}"
+echo -e "${g}   / _// _ \/ / _  / -_) __/${y}\ \/ // / _ \/ __/${s}"
+echo -e "${g}  /_/  \___/_/\_,_/\__/_/ ${y}/___/\_, /_//_/\__/ ${s}"
+echo -e "${g}                          ${y}    /___/           ${s}"
 echo -e ""
 
 # shellcheck disable=SC2031
 # shellcheck disable=SC2030
 if [ "$SERVICE" -eq 1 ]
 then
-    echo -e "${ansi_grn}Folder-sync started as background process; use '--stop' option to terminate it.${ansi_std}"
+    echo -e "${g}Folder-sync started as background process; use '--stop' option to terminate it.${s}"
     { (
         while /bin/true; do
-        checkAndDownload "$URL" "$CUT_OFF_TIME" "$OUT_DIR"
+        checkAndDownload "$URL" "$CUT_OFF_TIME" "$OUT_directory"
         sleep "$SLEEP"
 
-        CUT_OFF_TIME=$(getTimeMarker "$OUT_DIR") #update time marker
+        CUT_OFF_TIME=$(getTimeMarker "$OUT_directory") #update time marker
 #    done >>"$LOG" 2>&1 &
     done &); }>>"$LOG" 2>&1
 else
-    echo -e "${ansi_grn}Folder-sync running...${ansi_std}"
-    checkAndDownload "$URL" "$CUT_OFF_TIME" "$OUT_DIR"
+    echo -e "${g}Folder-sync running...${s}"
+    checkAndDownload "$URL" "$CUT_OFF_TIME" "$OUT_directory"
     if [[ ERR -eq 0 ]]
     then
-        echo -e "${ansi_grn}Folder-sync completed${ansi_std}"
+        echo -e "${g}Folder-sync completed${s}"
     else
-        echo -e "${ansi_yel}Folder-sync completed with errors${ansi_std}"
+        echo -e "${y}Folder-sync completed with errors${s}"
     fi
-    rm -Rf "$OUT_DIR/wrk"
+    rm -Rf "$OUT_directory/wrk"
 fi
 
 
