use shared memory for the curl jobs IPC

diff --git a/folder-sync b/folder-sync
--- a/folder-sync
+++ b/folder-sync
@@ -1,28 +1,7 @@
 #!/bin/bash
-
-#exec 3>&1 4>&2
-#trap 'exec 2>&4 1>&3' 0 1 2 3
-#exec 1>log.out 2>&1
-
-#(set -o igncr) 2>/dev/null && set -o igncr; # cygwin specific shell options
+(set -o igncr) 2>/dev/null && set -o igncr; # cygwin specific shell options
 #set -e
 #set -x
-
-SCRIPTS_LOGS_ROOT=.
-
-# no local logging if nested call
-(( ! IMPL_MODE && ! NEST_LVL )) && {
-    export IMPL_MODE=1
-    exec 3>&1 4>&2
-    trap 'exec 2>&4 1>&3' EXIT HUP INT QUIT RETURN
-
-    [[ ! -e "${SCRIPTS_LOGS_ROOT}/.log" ]] && mkdir "${SCRIPTS_LOGS_ROOT}/.log"
-
-    # RANDOM instead of milliseconds
-#    printf -v LOG_FILE_NAME_SUFFIX "%(%Y_%m_%d_%H_%M_%S_)T$(( RANDOM % 1000 ))" -1
-    printf -v LOG_FILE_NAME_SUFFIX "%(%Y_%m_%d)T" -1
-    (
-    (
 
 #     ____     __   __        ____
 #    / __/__  / /__/ /__ ____/ __/_ _____  ____
@@ -30,28 +9,23 @@ SCRIPTS_LOGS_ROOT=.
 #  /_/  \___/_/\_,_/\__/_/ /___/\_, /_//_/\__/
 #                              /___/
 
+## set trap commands
+#trap clean SIGINT SIGTERM
+#trap "exit" INT TERM ERR
+#trap "kill 0" EXIT # terminated all jobs on exit
+
 ###########################
 # functions
 ###########################
 
-# shellcheck disable=SC2034
-# for (( i = 30; i < 38; i++ )); do echo -e "\033[0;"$i"m Normal: (0;$i); \033[1;"$i"m Light: (1;$i)"; done
-r='\033[1;31m'
-g='\033[1;32m'
-y='\033[1;33m'
-b='\033[1;34m'
-c='\033[1;35m'
-b2='\033[1;36m'
-s='\033[0;37m'
-
 #exec 3>&1 4>&2 #set up extra file descriptors
-function catch-stderr() {
+function catchStdErr2() {
     local -n v="$1";
     shift && { v="$("$@" 2>&1 1>&3 3>&-)"; } 3>&1;
     echo "$v"
 }
 
-function catch-stderr2() {
+function catchStdErr() {
     local err=''
     { err="$("$@" 2>&1 1>&3 3>&-)"; } 3>&1
 
@@ -139,10 +113,10 @@ parseArgs() {
         -u | --user)     __argsmap[USER]=$2 ; shift 2 ;;
         -p | --password) __argsmap[PWD]=$2  ; shift 2 ;;
         -l | --logfile)  __argsmap[LOG]=$2  ; shift 2 ;;
-        -b ) __argsmap[SERVICE]=1; __argsmap[SLEEP]=$2; shift 2 ;;
         -m | --marker)   __argsmap[MARKER]=$(date -d "$2" '+%s'); shift 2 ;;
+        -b ) __argsmap[SERVICE]=1; __argsmap[SLEEP]=$2; shift 2 ;;
         --) shift; break ;;
-        *) echo "Unexpected option: $1" ; usage ;;
+        * ) echo "Unexpected option: $1" ; usage ;;
       esac
     done
 }
@@ -257,8 +231,7 @@ function getNewFiles() {
 
     # shellcheck disable=SC2068
     for f in ${_arr[@]}; do
-        # echo "f: [$f]" # todo check file is not empty
-        _lmd=$(getSourceLastModifiedDate "$_url/$f") #todo verify _lmd is not empty
+        _lmd=$(getSourceLastModifiedDate "$_url/$f")
         [ -n "$_lmd" ] || continue
         if [ "$_cutoff" -ge "$_lmd" ]; then
             print "\t(-) $f is old - skipped"
@@ -280,7 +253,6 @@ function showProgress() {
     local time="$6"
     local err="$7"
 
-    local b=1
     local kb=1024
     local mb=1048576
     local gb=1073741824
@@ -301,14 +273,14 @@ function showProgress() {
     if [[ $pct -lt 100 ]]; then status="${y}Downloading${s}"; else status="${g}Completed${s}"; fi
     if [[ $action == 'Canceled' ]]; then status="${r}FAILED${s}"; fi
 
-    printf  "%-15b" "$action"
+    printf "%-15b" "$action"
     printf "%-30s" "$file_name"
     printf "%6s / %-6s @ %6s %3s/sec (%3s%%)" $((completed/units)) $((file_size/units)) $((rate)) $scale $pct
     printf "%-25b" "......$status"
-    if [[ $action == 'Canceled' ]]; then printf "%40s" "[$err]"; fi
+    if [[ $action == 'Canceled' ]]; then printf "%40s\n" "[$err]"; fi
 }
 
-function download() {
+function downloadFile() {
     local SRC="$1"
     local DEST="$2"
     local NAME="$3"
@@ -319,7 +291,7 @@ function download() {
     mkdir -p "$WRK_directory" ; chmod 755 "$WRK_directory"
     [ -d "$OUT_directory" ] || { print "ERROR: Cannot create working directory [$WRK_directory]. Please check permissions"; exit; }
 
-    # [[ $NAME == 'BCDriverMerge.exe' ]] && NAME='*BCDriverMerge.exe' # just for testing
+     [[ $NAME == 'BCDriverMerge.exe' ]] && NAME='*BCDriverMerge.exe' # just for testing
     # curl --write-out "%{http_code}\n" -sS -R --ftp-pasv -u "$USER:$PWD" -o "${WRK_directory}/${NAME}.1" "$SRC/$NAME" >/dev/shm/fs 2>&1 &
     curl -sS -R --ftp-pasv -u "$USER:$PWD" -o "${WRK_directory}/${NAME}.1" "$SRC/$NAME" >/dev/shm/fs 2>&1 &
 
@@ -333,25 +305,24 @@ function download() {
         tput cub 1000 # move 1000 chars left
     done
 
-
     read -r job_response < /dev/shm/fs # get the job actual output
     job_err=$(jobs | awk '/Exit/ {print $3}') # or another way to get just the exit code
 
-    if [ "$job_err" == '' ]
-    then
+    if [ "$job_err" == '' ]; then
         showProgress 'Processed' "$WRK_directory" "$NAME" "$SPLIT_NUM" "$size" "$time"
     else
         showProgress 'Canceled' "$WRK_directory" "$NAME" "$SPLIT_NUM" "$size" "$time" "$job_response"
-        ((ERR++))
+        return 1
     fi
-    echo
+    echo # print line separator to complete the progress line
 
-    ERR_MSG=$(catch-stderr2 mv "${WRK_directory}/${NAME}.1" "$DEST/$NAME")
-    [ $? -ne 0 ] && [ "$job_response" == '' ] && { print "$ERR_MSG"; ((ERR++)); }
+    job_err=$(catchStdErr mv "${WRK_directory}/${NAME}.1" "$DEST/$NAME")
+    [ $? -ne 0 ] && return 1
+}
 
-    [ "$DELETE_REMOTE_FILE" = "y" ] && curl -u "$USER:$PWD" "$SRC" -Q"DELETE $SRC/$NAME" 2> /dev/null
-
-    return "$ERR"
+function removeRemoteFile() {
+    err_msg=$(catchStdErr curl -u "$1***" "$2" -Q"DELETE $2/$3") 2> /dev/null
+    echo "removeRemoteFile: $err_msg"
 }
 
 function print() {
@@ -365,16 +336,21 @@ function checkAndDownload() {
     local -a _files
 
     print ""
-    print "Checking for new files as off [$(date -d @"$_time")] in [$_url]"
+    print "Checking location [$_url] for files newer than [$(date -d @"$_time")]"
     getDirectoryContent _files "$_url"
     getNewFiles _files "$_url" "$_time"
 
     # shellcheck disable=SC2068
+    # todo support for parallel download
     for f in ${_files[@]}; do
         local _size=$(getSize "$_url/$f")
-        download "$_url" "$_out" "$f" "$_size"
-    done
+        downloadFile "$_url" "$_out" "$f" "$_size"
+        err2=$?
+        [ $? -ne 0 ] && { (( ERR_FLAG++)); echo -e "${y}Error reported for file $f [$err2]${s}"; }
 
+        [ "$DELETE_REMOTE_FILE" = "y" ] && err_msg=$(removeRemoteFile "$USER:$PWD" "$SRC" "$NAME")
+        [ "$err_msg" != '' ] && { (( ERR_FLAG++)); echo -e "${y}Error reported for file $f [$err_msg]${s}"; }
+    done
     return
 }
 
@@ -383,17 +359,52 @@ function main {
 }
 
 ###########################
-# main
+# parse args
 ###########################
-
 # shellcheck disable=SC2034
-ERR=0
 CMD_ARGS=("$@")
 declare -A ARGS_MAP
 parseArgs CMD_ARGS ARGS_MAP
 
 #todo verbose option
 #for K in "${!ARGS_MAP[@]}"; do echo "[$K] : [${ARGS_MAP[$K]}]"; done
+
+
+###############################
+# wrap all output for logging
+###############################
+LOGS_ROOT=.
+#exec 3>&1 4>&2
+#trap 'exec 2>&4 1>&3' 0 1 2 3
+#exec 1>log.out 2>&1
+
+(( ! log_init && ! script_init )) && {
+    export log_init=1
+    exec 3>&1 4>&2
+    trap 'exec 2>&4 1>&3' EXIT HUP INT QUIT RETURN
+
+    # set log level
+    LEVEL=${ARGS_MAP[LEVEL]:-2}
+    LOG=${ARGS_MAP[LOG]:-"$OUT_directory/log.txt"}
+
+    [[ ! -e "${LOGS_ROOT}/.log" ]] && mkdir "${LOGS_ROOT}/.log"
+
+    # generate log file suffix as preferred
+    # printf -v LOG_FILE_NAME_SUFFIX "%(%Y%m%d-%H%M%S-)T$(( RANDOM % 1000 ))" -1
+    printf -v LOG_FILE_NAME_SUFFIX "%(%Y_%m_%d)T" -1
+    LOG_FILE_NAME="${LOGS_ROOT}/.log/folder-sync.${LOG_FILE_NAME_SUFFIX}.log"
+
+    # re-enter the entire script to wrap and redirect output
+    ( (exec "$0" "$@") | tee -a "$LOG_FILE_NAME" 2>&1) 1>&3 2>&4
+
+    exit $?
+}
+(( script_init++ ))
+
+###########################
+# main
+###########################
+ERR_FLAG=0
 
 # validate required arguments
 [ ${ARGS_MAP[URL]+_} ] ||  usage "-s | --source"
@@ -421,29 +432,11 @@ PWD="${ARGS_MAP[PWD]}"
 SERVICE=${ARGS_MAP[SERVICE]:-0}
 SLEEP=${ARGS_MAP[SLEEP]:-60}
 
-# set log level
-LEVEL=${ARGS_MAP[LEVEL]:-2}
-LOG=${ARGS_MAP[LOG]:-"$OUT_directory/log.txt"}
+# ansi colors
+r='\033[1;31m' ; g='\033[1;32m'; y='\033[1;33m'; s='\033[0;37m'
 
-# todo: add verbose mode
-#print "URL" "$URL"
-#print "OUT_directory" "$OUT_directory"
-#print "USER" "$USER"
-#print "SERVICE" "$SERVICE"
-#print "SLEEP" "$SLEEP"
-#print "LEVEL" "$LEVEL"
-#print "LOG" "$LOG"
-#print "DELETE_REMOTE_FILE" "$DELETE_REMOTE_FILE"
-#print "CUT_OFF_TIME" "$(date -d "@$CUT_OFF_TIME")"
-
-## set trap commands
-#trap clean SIGINT SIGTERM
-#trap "exit" INT TERM ERR
-#trap "kill 0" EXIT # terminated all jobs on exit
-
-
-# logo
 # todo: option for silent
+# logo
 echo -e ""
 echo -e "${g}     ____     __   __       ${y} ____             ${s}"
 echo -e "${g}    / __/__  / /__/ /__ ____${y}/ __/_ _____  ____${s}"
@@ -464,11 +457,11 @@ then
 
         CUT_OFF_TIME=$(getTimeMarker "$OUT_directory") #update time marker
 #    done >>"$LOG" 2>&1 &
-    done &); }>>"$LOG" 2>&1
+    done &); } 2>&1
 else
     echo -e "${g}Folder-sync running...${s}"
     checkAndDownload "$URL" "$CUT_OFF_TIME" "$OUT_directory"
-    if [[ ERR -eq 0 ]]
+    if [ $ERR_FLAG -eq 0 ]
     then
         echo -e "${g}Folder-sync completed${s}"
     else
@@ -476,15 +469,3 @@ else
     fi
     rm -Rf "$OUT_directory/wrk"
 fi
-
-
-# end of logging wrapper function
-    # self script reentrance...
-    exec $0 "$@"
-    ) | tee -a "${SCRIPTS_LOGS_ROOT}/.log/folder-sync.${LOG_FILE_NAME_SUFFIX}.log" 2>&1
-    ) 1>&3 2>&4
-
-    exit $?
-}
-
-(( NEST_LVL++ ))
